<script>
	(window.Turbo || top.Turbo).message({
		NOTICE_ADDED2CART: "{$lang->added_cart}",
		NOTICE_CLOSE: "{$lang->close}",
		NOTICE_ERROR: "{$lang->error}",
		NOTICE_REQUEST_ERROR: "{$lang->the_request_failed}",
		NOTICE_RATING_ERROR: "{$lang->already_voted}",
		CT_BST_SEARCH_BUTTON2: "{$lang->find}",
		SEARCH_IN_SITE_FULL: "{$lang->all_site}",
		SEARCH_ALL_RESULTS: "{$lang->all_results}",
		SEARCH_IN_SITE: "{$lang->all_search}",
		SEARCH_IN_BLOG: "{$lang->global_blog}",
		SEARCH_IN_ARTICLE: "{$lang->global_articles}",
		SEARCH_IN_PROJECTS_FULL: "{$lang->by_projects}",
		SEARCH_IN_PROJECTS: "{$lang->global_projects}",
		JS_CORE_LOADING: "{$lang->loading}",
		JS_REQUIRED: "{$lang->error_required}",
		JS_FORMAT: "{$lang->error_format}",
		JS_PASSWORD_COPY: "{$lang->password_mismatch}",
		JS_PASSWORD_LENGTH: "{$lang->minimum_6_characters}",
		JS_ERROR: "{$lang->filled_in_incorrectly}",
		JS_REQUIRED_LICENSES: "{$lang->agree_to_the_terms}",
		FANCY_CLOSE: "{$lang->close}",
		FANCY_NEXT: "{$lang->next}",
		FANCY_PREV: "{$lang->previous}",
		SHOW: "{$lang->more_global}",
		HIDE: "{$lang->hide}",
		TS_T_light: "{$lang->enable_dark_theme}",
		TS_T_dark: "{$lang->enable_light_theme}",
		MORE_DETAIL_TEXT: "{$lang->moredetails}",
		HIDE_DETAIL_TEXT: "{$lang->hide}",
		LANGUAGE_ID: "{$language->label|escape}",
		FORMAT_DATE: "DD.MM.YYYY",
		FORMAT_DATETIME: "DD.MM.YYYY HH:MI:SS",
		turbo_sessid: "a1f39af03a4f2f8fa0a30fa07e4a7909",
	});
</script>