<script>
	(window.Turbo || top.Turbo).message({
		NOTICE_ADDED2CART: "{$lang->added_cart|escape}",
		NOTICE_CLOSE: "{$lang->close|escape}",
		NOTICE_ERROR: "{$lang->error|escape}",
		NOTICE_REQUEST_ERROR: "{$lang->the_request_failed|escape}",
		NOTICE_RATING_ERROR: "{$lang->already_voted|escape}",
		CT_BST_SEARCH_BUTTON2: "{$lang->find|escape}",
		SEARCH_IN_SITE_FULL: "{$lang->all_site|escape}",
		SEARCH_ALL_RESULTS: "{$lang->all_results|escape}",
		SEARCH_IN_SITE: "{$lang->all_search|escape}",
		SEARCH_IN_BLOG: "{$lang->global_blog|escape}",
		SEARCH_IN_ARTICLE: "{$lang->global_articles|escape}",
		SEARCH_IN_PROJECTS_FULL: "{$lang->by_projects|escape}",
		SEARCH_IN_PROJECTS: "{$lang->global_projects|escape}",
		JS_CORE_LOADING: "{$lang->loading|escape}",
		JS_REQUIRED: "{$lang->error_required|escape}",
		JS_FORMAT: "{$lang->error_format|escape}",
		JS_PASSWORD_COPY: "{$lang->password_mismatch|escape}",
		JS_PASSWORD_LENGTH: "{$lang->minimum_6_characters|escape}",
		JS_ERROR: "{$lang->filled_in_incorrectly|escape}",
		JS_REQUIRED_LICENSES: "{$lang->agree_to_the_terms|escape}",
		FANCY_CLOSE: "{$lang->close|escape}",
		FANCY_NEXT: "{$lang->next|escape}",
		FANCY_PREV: "{$lang->previous|escape}",
		SHOW: "{$lang->global_more|escape}",
		HIDE: "{$lang->hide|escape}",
		TS_T_light: "{$lang->enable_dark_theme|escape}",
		TS_T_dark: "{$lang->enable_light_theme|escape}",
		MORE_DETAIL_TEXT: "{$lang->moredetails|escape}",
		HIDE_DETAIL_TEXT: "{$lang->hide|escape}",
		LANGUAGE_ID: "{$language->label|escape}",
		FORMAT_DATE: "DD.MM.YYYY",
		FORMAT_DATETIME: "DD.MM.YYYY HH:MI:SS",
		turbo_sessid: "a1f39af03a4f2f8fa0a30fa07e4a7909",
	});
</script>